version: '3.3'

services:
  ucf-poll-mysql:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ucfpoll
    ports:
      - 3306:3306
  ucf-poll-dynamodb:
    command: '-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data'
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal
    restart: always

volumes:
  db_data: {}
